### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by jiisuominen** [mrprompt/deploybot-cli#6]
Hey!

This may be a bit stupid question, but how do I configure this client? Ie, where to put DeployBot credentials so that app knows to use them?

I have installed this via pip and I just can' figure out where to put credentials to be able to use this client.

Cheers,
Janne

**Comment by mdix** [comment]
You missed https://github.com/mrprompt/deploybot-cli#configuration, did you?

It's configured using environment variables, see https://github.com/mrprompt/deploybot-cli/blob/master/cli/config.py.

Check this on how to do it: https://www.cyberciti.biz/faq/set-environment-variable-linux/

**Comment by mrprompt** [comment]
tks @mdix

**Comment by jiisuominen** [comment]
Oh. Ohhhhhh.

I didn't miss that configuration part, though I definitely missed that environment variable thing. 

Thanks a lot!

/ Janne
